# Generated by Django 4.0.6 on 2022-07-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='sensor_id',
        ),
        migrations.AddField(
            model_name='measurement',
            name='sensor_id',
            field=models.ManyToManyField(related_name='measurements', to='measurement.sensor'),
        ),
    ]
